<?php
	$ServerInfo = $MyPhp->plugin('server_info');
?>
<nav>
  <ul>
  	<li>	<a data-do="menu" data-target="#main">Back</a></li>
  </ul>
</nav>
<div class="main wrapper clearfix">
    <article>
        <header>
            <h1>Ultimate Cheatsheet</h1>
            <p>
													Ultimate cheatsheet is a mobile app developed by Adam Dougherty to demonstrate the PScript engine.
												</p>
        </header>
    </article>

    <aside>
        <p>Copyright (c) Adam Dougherty 2016</p>
    </aside>
    
    <?php $ServerInfo->phpinfo(); ?>
    
    <?php $Blocks->plugin('server_info', 'php_info', $MyPhp); ?>

</div> <!-- #main -->