    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Fill in the form below...</h2>
          
<?php
	$contact = $MyPhp->myPhp('contact');
	$errors = false;
	if(isset($_POST['name'])) {
				$errors = $contact->validate($_POST);
	}
?>


<?php if($errors === true): ?>
	
	<p>Thankyou for getting in touch!</p>
	
<?php else: ?>

<form id='contact' method="post" class='contact-form'>
	<label for="name">Name: </label><input type="text" name="name"/>
	<?php if(@$errors['name']): ?>
			<span class='error'><?php echo $errors['name']; ?></span>
		<?php endif; ?>
		
		<label for="email">Email: </label><input type="text" name="email"/>
	<?php if(@$errors['email']): ?>
			<span class='error'><?php echo $errors['name']; ?></span>
		<?php endif; ?>
		
		<label for="message">Message: </label><textarea name="message"></textarea>
	<?php if(@$errors['message']): ?>
			<span class='error'><?php echo $errors['name']; ?></span>
		<?php endif; ?>
		
</form>
<button class='button-action btn btn-default' data-post='contact_form' data-target="#contact-form" data-form="#contact" data-transition="fade">Send Message</button>

<?php endif; ?>

        </div>
        
      </div>
