
						<div class="jumbotron">
							<div class="container">
								<div class="row">
							<div class="col-sm-6">
								<h2>Yummy from above</h2>
	       <div id="chart_div"></div>
       </div>
       <div class="col-sm-6">
       	<h2>Your App</h2>
       	<div id="chart_div2"></div>
       </div>
       </div>
      </div>
      <br />
      </div>
       
       
   <script type="text/javascript">
   
   	addJS('var gLoaded= gLoaded || false;');

   	addJSURL('https://www.gstatic.com/charts/loader.js');

   	setTimeout(function(){
						if(gLoaded===false) {
								
	   	   google.charts.load('current', {packages:["orgchart"]});
			     google.charts.setOnLoadCallback(drawChart);
								gLoaded = true;
							}
      function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Name');
        data.addColumn('string', 'Manager');
        data.addColumn('string', 'ToolTip');

        // For each orgchart box, provide the name, manager, and tooltip to show.
        data.addRows([
          ['Your App', '', 'App'],
          
          ['Yummy Berry', 'Your App', 'myapp'],
          ['JS Engine', 'Yummy Berry', ''],
          ['Plugins', 'Yummy Berry', ''],
          ['PHP Engine', 'Yummy Berry', 'A couple of helpers classes to put everything together'],
        ]);

        // Create the chart.
        var chart = new google.visualization.OrgChart(document.getElementById('chart_div'));
        // Draw the chart, setting the allowHtml option to true for the tooltips.
        chart.draw(data, {allowHtml:true});
        
        
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Name');
        data.addColumn('string', 'Manager');
        data.addColumn('string', 'ToolTip');

        // For each orgchart box, provide the name, manager, and tooltip to show.
        data.addRows([
          ['Your App', '', 'App'],
          ['Themes', 'Your App', ''],
          ['Pages', 'Your App', ''],
          ['Blocks', 'Your App', ''],
          ['PHP', 'Your App', ''],
          ['JS', 'Your App', ''],
        ]);

        // Create the chart.
        var chart = new google.visualization.OrgChart(document.getElementById('chart_div2'));
        // Draw the chart, setting the allowHtml option to true for the tooltips.
        chart.draw(data, {allowHtml:true});
        
      }
      	setTimeout(function() {drawChart();},1000);
      
      
   	}, 1000);
   </script>

    