<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron ">
    	<div class="center-block">
        <h2>Let's take a look...</h2>
        </p>
        
    </div>
   </div>
   <div class="container">
<h3 class='page-header'>Load a block serverside</h3>
<p>A 'block' is a piece of PHP or HTML which can be called in to code anywhere.</p>

<?php
$data = array();
$data['source_sample'] = "
/* Load any piece of code from anywhere in your pages */

<div class='page-content' id='page-content'>
 <div class='main-container' id='main'>
  <?php \$Blocks->get('menu', \$MyPhp); ?>   
 </div>
 
</div>

";
$Blocks->data($data);
$Blocks->get('code_sample');
?>

<h3 class='page-header'>Load a block click side on click</h3>
<p>A 'block' is a piece of PHP or HTML which can be called in to code anywhere.</p>
<?php
$data = array();
$data['source_sample'] = "

/* Load that same piece of code with ajax after an event */

<button data-do='menu' data-target='#main'>Menu</button>

";
$Blocks->data($data);
$Blocks->get('code_sample');
?>

<h3 class='page-header'>Sample structure</h3>

<?php
$dirs['myapp'] = array(
"config.php (Your apps settings)",
"blocks"=>array("login.phtml", "register.phtml", "menu.phtml"),
"pages"=>array("home.phtml", "admin.phtml"),
"php"=>array("customers.php", "leads.php"),
"theme"=>array("master.phtml", "css"=>array("styles.css"), "img"=>array("logo.png"))
);
$Blocks->data(array("util_dirs"=>$dirs));
$desc = "Your site can be organised in just a couple of folders which glue everything together for re-usability";
$Blocks->data(array("util_dirs_desc"=>$desc));
?>
<?php $Blocks -> plugin('utilities', 'directory_list', $MyPhp); ?>

<br />