	<div class="header-container">
            <header class="wrapper clearfix">
                <h1 class="title">h1.title</h1>
                <nav>
                    <ul>
                        <li><a data-do="about_us" data-transition="fade" data-target="#main">About us</a></li>
                        <li><a  data-do="samples" data-target="#main">Samples</a></li>
                        <li><a data-do="contact_form" data-target="#main">Get in touch</a></li>
                    </ul>
                </nav>
            </header>
        </div>