<div class="header-container">
<header class="wrapper clearfix">
    <h1 class="title">Ultimate Cheatsheet</h1>
    <nav>
        <ul>
            <li><a data-do="about_us" data-transition="fade" data-target="#main">About Ultimate Cheatsheet</a></li>
            <li><a data-do="cheat_php" data-target="#main">PHP</a></li>
            <li><a data-do="get_in_touch" data-target="#main">Get in touch</a></li>
            <li><a data-do="plugins/server_info/overview" data-target="#main">Server Overview</a></li>
        </ul>
    </nav>
</header>
</div>